export const NIGERIAN_UNIVERSITIES = [
  "University of Lagos (UNILAG)",
  "University of Ibadan (UI)",
  "Obafemi Awolowo University (OAU)",
  "Federal University of Technology Akure (FUTA)",
  "Ahmadu Bello University (ABU Zaria)",
  "Lagos State University (LASU)",
  "University of Port Harcourt (UNIPORT)",
  "University of Benin (UNIBEN)",
  "University of Nigeria Nsukka (UNN)",
  "University of Abuja (UNIABUJA)",
  "Covenant University",
  "Babcock University",
  "Bayero University Kano (BUK)",
  "University of Ilorin (UNILORIN)",
  "Federal University of Technology Minna (FUTMINNA)",
  "Federal University of Technology Owerri (FUTO)",
  "University of Jos (UNIJOS)",
  "University of Calabar (UNICAL)",
  "University of Uyo (UNIUYO)",
  "Nnamdi Azikiwe University (UNIZIK)",
  "Federal University Oye-Ekiti (FUOYE)",
  "Pan-Atlantic University",
  "Afe Babalola University (ABUAD)",
  "Bowen University",
  "Redeemer's University",
  "Lead City University",
  "American University of Nigeria (AUN)",
  "Igbinedion University",
  "Caleb University",
  "Crescent University",
  "Olabisi Onabanjo University (OOU)",
  "Ekiti State University (EKSU)",
  "Tai Solarin University of Education",
  "Lagos State University of Education (LASUED)",
  "Adekunle Ajasin University (AAUA)",
  "Federal University Lokoja",
  "Federal University Dutse",
  "Federal University Kashere",
  "Federal University Otuoke",
  "Federal University Lafia",
  "Federal University Wukari",
  "Federal University Birnin Kebbi",
  "Federal University Gusau",
  "Federal University Dutsin-Ma",
  "Federal University Ndufu-Alike Ikwo",
  "Modibbo Adama University Yola",
  "Usmanu Danfodiyo University",
  "University of Maiduguri (UNIMAID)",
  "Ladoke Akintola University of Technology (LAUTECH)",
  "Rivers State University",
  "Other",
];

export const YEARS_OF_STUDY = [
  "100 level",
  "200 level",
  "300 level",
  "400 level",
  "500 level and above",
];


export const SKILLS = [
  "Web Design",
  "Mobile App Dev",
  "UI/UX Design",
  "Graphic Design",
  "Content Writing",
  "Copywriting",
  "Social Media",
  "Video Editing",
  "Photography",
  "Data Analysis",
  "Research",
  "Python",
  "JavaScript",
  "Excel/Spreadsheets",
  "Tutoring (Math)",
  "Tutoring (Sciences)",
  "Tutoring (English)",
  "Business Analysis",
  "Product Management",
  "Virtual Assistant",
  "Frontend Development",
  "Backend Development",
  "Full Stack Development",
  "WordPress Development",
  "SEO",
  "SEM/Paid Ads",
  "Email Marketing",
  "Brand Strategy",
  "Motion Graphics",
  "3D Modeling",
  "Illustration",
  "Sound Design",
  "Podcast Editing",
  "Cinematography",
  "Data Visualization",
  "SQL",
  "Power BI",
  "Tableau",
  "Financial Modeling",
  "Accounting & Bookkeeping",
  "Market Research",
  "Operations Management",
  "Project Coordination",
  "Customer Support",
  "CRM Management",
  "Lead Generation",
  "Sales Outreach",
  "Community Management",
  "HR & Recruiting",
  "Technical Writing",
  "Grant Writing",
  "Translation",
  "Transcription",
  "Proofreading & Editing",
  "Presentation Design",
  "Cybersecurity",
  "DevOps",
  "Cloud Computing",
  "AI/ML",
  "No-Code Automation",
  "Mobile UI Design",
  "QA Testing",
  "Game Development",
  "Blockchain Development",
  "Legal Research",
  "Administrative Support",
  "Event Planning",
  "E-commerce Management",
  "Shopify Management",
  "Video Production",
  "Script Writing",
  "Public Speaking Coaching",
  "Career Coaching",
  "Interview Coaching",
  "Academic Tutoring",
  "STEM Tutoring",
  "Language Tutoring",
  "Resume Writing",
  "Portfolio Design",
  "Git/GitHub",
  "React",
  "Node.js",
  "Django",
  "Flutter",
  "Kotlin",
  "Swift",
  "AWS",
  "Google Cloud",
  "Linux Administration",
  "Database Design",
  "API Integration",
  "Automation Scripting",
  "Stakeholder Communication",
  "Time Management",
  "Problem Solving",
  "Client Relations",
  "Negotiation",
  "Documentation",
  "Workshop Facilitation",
  "User Research",
  "Product Discovery",
  "Business Process Mapping",
  "Data Entry",
  "Virtual Event Hosting",
  "Canva Design",
  "Figma",
  "Adobe Photoshop",
  "Adobe Premiere Pro",
];

export const TASK_CATEGORIES = [
  "Web Design",
  "Mobile Dev",
  "Software Development",
  "UI/UX Design",
  "Graphic Design",
  "Design & Creative",
  "Content Writing",
  "Video/Photo",
  "Marketing & Growth",
  "Research",
  "Tutoring",
  "Business",
  "Data & Analytics",
  "Virtual Assistant",
  "Cybersecurity",
  "DevOps & Cloud",
  "AI & Machine Learning",
  "E-commerce",
  "Customer Support",
  "Sales & Outreach",
  "HR & Recruiting",
  "Legal & Compliance",
  "Event & Community",
  "Translation & Transcription",
  "Other",
];

export const TASK_CATEGORY_SKILLS: Record<string, string[]> = {
  "Web Design": ["Web Design", "UI/UX Design", "Frontend Development", "JavaScript", "React", "Figma", "SEO", "WordPress Development", "Canva Design", "Graphic Design"],
  "Mobile Dev": ["Mobile App Dev", "Mobile UI Design", "Flutter", "Kotlin", "Swift", "UI/UX Design", "JavaScript", "React", "QA Testing", "API Integration"],
  "Software Development": ["Full Stack Development", "Frontend Development", "Backend Development", "JavaScript", "Python", "React", "Node.js", "Django", "Database Design", "Git/GitHub"],
  "UI/UX Design": ["UI/UX Design", "User Research", "Product Discovery", "Figma", "Presentation Design", "Web Design", "Mobile UI Design", "Canva Design", "Graphic Design", "Portfolio Design"],
  "Graphic Design": ["Graphic Design", "Illustration", "Brand Strategy", "Adobe Photoshop", "Canva Design", "Presentation Design", "Motion Graphics", "Photography", "Figma", "Portfolio Design"],
  "Design & Creative": ["Graphic Design", "UI/UX Design", "Illustration", "3D Modeling", "Motion Graphics", "Adobe Photoshop", "Video Production", "Photography", "Script Writing", "Brand Strategy"],
  "Content Writing": ["Content Writing", "Copywriting", "Technical Writing", "Proofreading & Editing", "SEO", "Script Writing", "Grant Writing", "Research", "Documentation", "Resume Writing"],
  "Video/Photo": ["Video Editing", "Video Production", "Photography", "Cinematography", "Motion Graphics", "Adobe Premiere Pro", "Sound Design", "Podcast Editing", "Script Writing", "Social Media"],
  "Marketing & Growth": ["SEO", "SEM/Paid Ads", "Email Marketing", "Social Media", "Brand Strategy", "Copywriting", "Community Management", "Lead Generation", "Data Analysis", "Market Research"],
  "Research": ["Research", "Market Research", "Data Analysis", "Data Visualization", "SQL", "Excel/Spreadsheets", "Technical Writing", "Documentation", "Business Analysis", "Legal Research"],
  "Tutoring": ["Tutoring (Math)", "Tutoring (Sciences)", "Tutoring (English)", "Academic Tutoring", "STEM Tutoring", "Language Tutoring", "Public Speaking Coaching", "Career Coaching", "Interview Coaching", "Research"],
  "Business": ["Business Analysis", "Product Management", "Financial Modeling", "Accounting & Bookkeeping", "Operations Management", "Project Coordination", "Stakeholder Communication", "Business Process Mapping", "CRM Management", "Negotiation"],
  "Data & Analytics": ["Data Analysis", "Data Visualization", "SQL", "Power BI", "Tableau", "Excel/Spreadsheets", "Python", "Business Analysis", "Market Research", "Automation Scripting"],
  "Virtual Assistant": ["Virtual Assistant", "Administrative Support", "Data Entry", "CRM Management", "Customer Support", "Project Coordination", "Email Marketing", "Documentation", "Time Management", "Client Relations"],
  "Cybersecurity": ["Cybersecurity", "Linux Administration", "Cloud Computing", "DevOps", "Problem Solving", "Documentation", "API Integration", "Database Design", "Automation Scripting", "Stakeholder Communication"],
  "DevOps & Cloud": ["DevOps", "Cloud Computing", "AWS", "Google Cloud", "Linux Administration", "Database Design", "API Integration", "Automation Scripting", "Git/GitHub", "Backend Development"],
  "AI & Machine Learning": ["AI/ML", "Python", "Data Analysis", "Data Visualization", "SQL", "Automation Scripting", "Cloud Computing", "Research", "Problem Solving", "Technical Writing"],
  "E-commerce": ["E-commerce Management", "Shopify Management", "SEO", "Copywriting", "Graphic Design", "Customer Support", "CRM Management", "Data Analysis", "Email Marketing", "Sales Outreach"],
  "Customer Support": ["Customer Support", "Client Relations", "CRM Management", "Virtual Assistant", "Problem Solving", "Stakeholder Communication", "Documentation", "Time Management", "Community Management", "Translation"],
  "Sales & Outreach": ["Sales Outreach", "Lead Generation", "Copywriting", "CRM Management", "Client Relations", "Negotiation", "Email Marketing", "Social Media", "Market Research", "Presentation Design"],
  "HR & Recruiting": ["HR & Recruiting", "Interview Coaching", "Resume Writing", "Career Coaching", "Stakeholder Communication", "Documentation", "Project Coordination", "Client Relations", "Market Research", "Data Analysis"],
  "Legal & Compliance": ["Legal Research", "Documentation", "Technical Writing", "Research", "Stakeholder Communication", "Business Analysis", "Proofreading & Editing", "Project Coordination", "Data Analysis", "Client Relations"],
  "Event & Community": ["Event Planning", "Community Management", "Virtual Event Hosting", "Public Speaking Coaching", "Social Media", "Project Coordination", "Client Relations", "Presentation Design", "Brand Strategy", "Workshop Facilitation"],
  "Translation & Transcription": ["Translation", "Transcription", "Proofreading & Editing", "Content Writing", "Documentation", "Research", "Customer Support", "Time Management", "Client Relations", "Technical Writing"],
  "Other": SKILLS,
};

export function getSkillsForTaskCategory(category?: string) {
  if (!category) return SKILLS;
  return TASK_CATEGORY_SKILLS[category] ?? SKILLS;
}

export const FEED_FILTERS = [
  "All",
  ...TASK_CATEGORIES,
];

export const NG_PHONE_REGEX = /^(?:\+234|0)(70|80|81|90|91|71)\d{8}$/;
