export const NIGERIAN_UNIVERSITIES = [
  "University of Lagos (UNILAG)",
  "University of Ibadan (UI)",
  "Obafemi Awolowo University (OAU)",
  "Federal University of Technology Akure (FUTA)",
  "Ahmadu Bello University (ABU Zaria)",
  "Lagos State University (LASU)",
  "University of Port Harcourt (UNIPORT)",
  "University of Benin (UNIBEN)",
  "University of Nigeria Nsukka (UNN)",
  "University of Abuja (UNIABUJA)",
  "Covenant University",
  "Babcock University",
  "Bayero University Kano (BUK)",
  "University of Ilorin (UNILORIN)",
  "Federal University of Technology Minna (FUTMINNA)",
  "Federal University of Technology Owerri (FUTO)",
  "University of Jos (UNIJOS)",
  "University of Calabar (UNICAL)",
  "University of Uyo (UNIUYO)",
  "Nnamdi Azikiwe University (UNIZIK)",
  "Federal University Oye-Ekiti (FUOYE)",
  "Pan-Atlantic University",
  "Afe Babalola University (ABUAD)",
  "Bowen University",
  "Redeemer's University",
  "Lead City University",
  "American University of Nigeria (AUN)",
  "Igbinedion University",
  "Caleb University",
  "Crescent University",
  "Olabisi Onabanjo University (OOU)",
  "Ekiti State University (EKSU)",
  "Tai Solarin University of Education",
  "Lagos State University of Education (LASUED)",
  "Adekunle Ajasin University (AAUA)",
  "Federal University Lokoja",
  "Federal University Dutse",
  "Federal University Kashere",
  "Federal University Otuoke",
  "Federal University Lafia",
  "Federal University Wukari",
  "Federal University Birnin Kebbi",
  "Federal University Gusau",
  "Federal University Dutsin-Ma",
  "Federal University Ndufu-Alike Ikwo",
  "Modibbo Adama University Yola",
  "Usmanu Danfodiyo University",
  "University of Maiduguri (UNIMAID)",
  "Ladoke Akintola University of Technology (LAUTECH)",
  "Rivers State University",
  "Other",
];

export const YEARS_OF_STUDY = [
  "100 level",
  "200 level",
  "300 level",
  "400 level",
  "500 level and above",
];


export const SKILLS = [
  "Web Design",
  "Mobile App Dev",
  "UI/UX Design",
  "Graphic Design",
  "Content Writing",
  "Copywriting",
  "Social Media",
  "Video Editing",
  "Photography",
  "Data Analysis",
  "Research",
  "Python",
  "JavaScript",
  "Excel/Spreadsheets",
  "Tutoring (Math)",
  "Tutoring (Sciences)",
  "Tutoring (English)",
  "Business Analysis",
  "Product Management",
  "Virtual Assistant",
];

export const TASK_CATEGORIES = [
  "Web Design",
  "Mobile Dev",
  "Graphic Design",
  "Content Writing",
  "Video/Photo",
  "Research",
  "Tutoring",
  "Business",
  "Virtual Assistant",
  "Other",
];

export const FEED_FILTERS = [
  "All",
  "Web Design",
  "Writing",
  "Design",
  "Research",
  "Tutoring",
  "Tech",
  "Business",
];

export const NG_PHONE_REGEX = /^(?:\+234|0)(70|80|81|90|91|71)\d{8}$/;
