/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AppWalletRouteImport } from './routes/app.wallet'
import { Route as AppTalentRouteImport } from './routes/app.talent'
import { Route as AppSubscriptionRouteImport } from './routes/app.subscription'
import { Route as AppPartnershipRouteImport } from './routes/app.partnership'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppMentorshipRouteImport } from './routes/app.mentorship'
import { Route as AppLearnRouteImport } from './routes/app.learn'
import { Route as AppInternshipsRouteImport } from './routes/app.internships'
import { Route as AppBrowseRouteImport } from './routes/app.browse'
import { Route as AppAssessmentsRouteImport } from './routes/app.assessments'
import { Route as AppAlumniProRouteImport } from './routes/app.alumni-pro'
import { Route as AppTasksCreateRouteImport } from './routes/app.tasks.create'
import { Route as AppRoomsRoomIdRouteImport } from './routes/app.rooms.$roomId'
import { Route as AppProfileUserIdRouteImport } from './routes/app.profile.$userId'
import { Route as AppPaymentTaskIdRouteImport } from './routes/app.payment.$taskId'
import { Route as AppMessagesConversationIdRouteImport } from './routes/app.messages.$conversationId'
import { Route as AppMentorshipManageRouteImport } from './routes/app.mentorship.manage'
import { Route as AppMentorshipBookingsRouteImport } from './routes/app.mentorship.bookings'
import { Route as AppMentorshipServiceIdRouteImport } from './routes/app.mentorship.$serviceId'
import { Route as AppLearnCourseIdRouteImport } from './routes/app.learn.$courseId'
import { Route as AppTasksTaskIdIndexRouteImport } from './routes/app.tasks.$taskId.index'
import { Route as AppTasksTaskIdReviewRouteImport } from './routes/app.tasks.$taskId.review'
import { Route as AppTasksTaskIdRateRouteImport } from './routes/app.tasks.$taskId.rate'
import { Route as AppTasksTaskIdDeliverRouteImport } from './routes/app.tasks.$taskId.deliver'
import { Route as AppTasksTaskIdApplicantsRouteImport } from './routes/app.tasks.$taskId.applicants'
import { Route as AppTasksTaskIdAnalyticsRouteImport } from './routes/app.tasks.$taskId.analytics'
import { Route as ApiPublicWebhooksPaystackRouteImport } from './routes/api/public/webhooks/paystack'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppTalentRoute = AppTalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppPartnershipRoute = AppPartnershipRouteImport.update({
  id: '/partnership',
  path: '/partnership',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppMentorshipRoute = AppMentorshipRouteImport.update({
  id: '/mentorship',
  path: '/mentorship',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnRoute = AppLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AppRoute,
} as any)
const AppInternshipsRoute = AppInternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => AppRoute,
} as any)
const AppBrowseRoute = AppBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentsRoute = AppAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => AppRoute,
} as any)
const AppAlumniProRoute = AppAlumniProRouteImport.update({
  id: '/alumni-pro',
  path: '/alumni-pro',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksCreateRoute = AppTasksCreateRouteImport.update({
  id: '/tasks/create',
  path: '/tasks/create',
  getParentRoute: () => AppRoute,
} as any)
const AppRoomsRoomIdRoute = AppRoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileUserIdRoute = AppProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentTaskIdRoute = AppPaymentTaskIdRouteImport.update({
  id: '/payment/$taskId',
  path: '/payment/$taskId',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesConversationIdRoute =
  AppMessagesConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AppMessagesRoute,
  } as any)
const AppMentorshipManageRoute = AppMentorshipManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => AppMentorshipRoute,
} as any)
const AppMentorshipBookingsRoute = AppMentorshipBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppMentorshipRoute,
} as any)
const AppMentorshipServiceIdRoute = AppMentorshipServiceIdRouteImport.update({
  id: '/$serviceId',
  path: '/$serviceId',
  getParentRoute: () => AppMentorshipRoute,
} as any)
const AppLearnCourseIdRoute = AppLearnCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => AppLearnRoute,
} as any)
const AppTasksTaskIdIndexRoute = AppTasksTaskIdIndexRouteImport.update({
  id: '/tasks/$taskId/',
  path: '/tasks/$taskId/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksTaskIdReviewRoute = AppTasksTaskIdReviewRouteImport.update({
  id: '/tasks/$taskId/review',
  path: '/tasks/$taskId/review',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksTaskIdRateRoute = AppTasksTaskIdRateRouteImport.update({
  id: '/tasks/$taskId/rate',
  path: '/tasks/$taskId/rate',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksTaskIdDeliverRoute = AppTasksTaskIdDeliverRouteImport.update({
  id: '/tasks/$taskId/deliver',
  path: '/tasks/$taskId/deliver',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksTaskIdApplicantsRoute =
  AppTasksTaskIdApplicantsRouteImport.update({
    id: '/tasks/$taskId/applicants',
    path: '/tasks/$taskId/applicants',
    getParentRoute: () => AppRoute,
  } as any)
const AppTasksTaskIdAnalyticsRoute = AppTasksTaskIdAnalyticsRouteImport.update({
  id: '/tasks/$taskId/analytics',
  path: '/tasks/$taskId/analytics',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicWebhooksPaystackRoute =
  ApiPublicWebhooksPaystackRouteImport.update({
    id: '/api/public/webhooks/paystack',
    path: '/api/public/webhooks/paystack',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/alumni-pro': typeof AppAlumniProRoute
  '/app/assessments': typeof AppAssessmentsRoute
  '/app/browse': typeof AppBrowseRoute
  '/app/internships': typeof AppInternshipsRoute
  '/app/learn': typeof AppLearnRouteWithChildren
  '/app/mentorship': typeof AppMentorshipRouteWithChildren
  '/app/messages': typeof AppMessagesRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/partnership': typeof AppPartnershipRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/talent': typeof AppTalentRoute
  '/app/wallet': typeof AppWalletRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app/': typeof AppIndexRoute
  '/app/learn/$courseId': typeof AppLearnCourseIdRoute
  '/app/mentorship/$serviceId': typeof AppMentorshipServiceIdRoute
  '/app/mentorship/bookings': typeof AppMentorshipBookingsRoute
  '/app/mentorship/manage': typeof AppMentorshipManageRoute
  '/app/messages/$conversationId': typeof AppMessagesConversationIdRoute
  '/app/payment/$taskId': typeof AppPaymentTaskIdRoute
  '/app/profile/$userId': typeof AppProfileUserIdRoute
  '/app/rooms/$roomId': typeof AppRoomsRoomIdRoute
  '/app/tasks/create': typeof AppTasksCreateRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
  '/app/tasks/$taskId/analytics': typeof AppTasksTaskIdAnalyticsRoute
  '/app/tasks/$taskId/applicants': typeof AppTasksTaskIdApplicantsRoute
  '/app/tasks/$taskId/deliver': typeof AppTasksTaskIdDeliverRoute
  '/app/tasks/$taskId/rate': typeof AppTasksTaskIdRateRoute
  '/app/tasks/$taskId/review': typeof AppTasksTaskIdReviewRoute
  '/app/tasks/$taskId/': typeof AppTasksTaskIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/alumni-pro': typeof AppAlumniProRoute
  '/app/assessments': typeof AppAssessmentsRoute
  '/app/browse': typeof AppBrowseRoute
  '/app/internships': typeof AppInternshipsRoute
  '/app/learn': typeof AppLearnRouteWithChildren
  '/app/mentorship': typeof AppMentorshipRouteWithChildren
  '/app/messages': typeof AppMessagesRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/partnership': typeof AppPartnershipRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/talent': typeof AppTalentRoute
  '/app/wallet': typeof AppWalletRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app': typeof AppIndexRoute
  '/app/learn/$courseId': typeof AppLearnCourseIdRoute
  '/app/mentorship/$serviceId': typeof AppMentorshipServiceIdRoute
  '/app/mentorship/bookings': typeof AppMentorshipBookingsRoute
  '/app/mentorship/manage': typeof AppMentorshipManageRoute
  '/app/messages/$conversationId': typeof AppMessagesConversationIdRoute
  '/app/payment/$taskId': typeof AppPaymentTaskIdRoute
  '/app/profile/$userId': typeof AppProfileUserIdRoute
  '/app/rooms/$roomId': typeof AppRoomsRoomIdRoute
  '/app/tasks/create': typeof AppTasksCreateRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
  '/app/tasks/$taskId/analytics': typeof AppTasksTaskIdAnalyticsRoute
  '/app/tasks/$taskId/applicants': typeof AppTasksTaskIdApplicantsRoute
  '/app/tasks/$taskId/deliver': typeof AppTasksTaskIdDeliverRoute
  '/app/tasks/$taskId/rate': typeof AppTasksTaskIdRateRoute
  '/app/tasks/$taskId/review': typeof AppTasksTaskIdReviewRoute
  '/app/tasks/$taskId': typeof AppTasksTaskIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/alumni-pro': typeof AppAlumniProRoute
  '/app/assessments': typeof AppAssessmentsRoute
  '/app/browse': typeof AppBrowseRoute
  '/app/internships': typeof AppInternshipsRoute
  '/app/learn': typeof AppLearnRouteWithChildren
  '/app/mentorship': typeof AppMentorshipRouteWithChildren
  '/app/messages': typeof AppMessagesRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/partnership': typeof AppPartnershipRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/talent': typeof AppTalentRoute
  '/app/wallet': typeof AppWalletRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app/': typeof AppIndexRoute
  '/app/learn/$courseId': typeof AppLearnCourseIdRoute
  '/app/mentorship/$serviceId': typeof AppMentorshipServiceIdRoute
  '/app/mentorship/bookings': typeof AppMentorshipBookingsRoute
  '/app/mentorship/manage': typeof AppMentorshipManageRoute
  '/app/messages/$conversationId': typeof AppMessagesConversationIdRoute
  '/app/payment/$taskId': typeof AppPaymentTaskIdRoute
  '/app/profile/$userId': typeof AppProfileUserIdRoute
  '/app/rooms/$roomId': typeof AppRoomsRoomIdRoute
  '/app/tasks/create': typeof AppTasksCreateRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
  '/app/tasks/$taskId/analytics': typeof AppTasksTaskIdAnalyticsRoute
  '/app/tasks/$taskId/applicants': typeof AppTasksTaskIdApplicantsRoute
  '/app/tasks/$taskId/deliver': typeof AppTasksTaskIdDeliverRoute
  '/app/tasks/$taskId/rate': typeof AppTasksTaskIdRateRoute
  '/app/tasks/$taskId/review': typeof AppTasksTaskIdReviewRoute
  '/app/tasks/$taskId/': typeof AppTasksTaskIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/sitemap.xml'
    | '/app/alumni-pro'
    | '/app/assessments'
    | '/app/browse'
    | '/app/internships'
    | '/app/learn'
    | '/app/mentorship'
    | '/app/messages'
    | '/app/notifications'
    | '/app/partnership'
    | '/app/subscription'
    | '/app/talent'
    | '/app/wallet'
    | '/auth/login'
    | '/auth/signup'
    | '/app/'
    | '/app/learn/$courseId'
    | '/app/mentorship/$serviceId'
    | '/app/mentorship/bookings'
    | '/app/mentorship/manage'
    | '/app/messages/$conversationId'
    | '/app/payment/$taskId'
    | '/app/profile/$userId'
    | '/app/rooms/$roomId'
    | '/app/tasks/create'
    | '/api/public/webhooks/paystack'
    | '/app/tasks/$taskId/analytics'
    | '/app/tasks/$taskId/applicants'
    | '/app/tasks/$taskId/deliver'
    | '/app/tasks/$taskId/rate'
    | '/app/tasks/$taskId/review'
    | '/app/tasks/$taskId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/sitemap.xml'
    | '/app/alumni-pro'
    | '/app/assessments'
    | '/app/browse'
    | '/app/internships'
    | '/app/learn'
    | '/app/mentorship'
    | '/app/messages'
    | '/app/notifications'
    | '/app/partnership'
    | '/app/subscription'
    | '/app/talent'
    | '/app/wallet'
    | '/auth/login'
    | '/auth/signup'
    | '/app'
    | '/app/learn/$courseId'
    | '/app/mentorship/$serviceId'
    | '/app/mentorship/bookings'
    | '/app/mentorship/manage'
    | '/app/messages/$conversationId'
    | '/app/payment/$taskId'
    | '/app/profile/$userId'
    | '/app/rooms/$roomId'
    | '/app/tasks/create'
    | '/api/public/webhooks/paystack'
    | '/app/tasks/$taskId/analytics'
    | '/app/tasks/$taskId/applicants'
    | '/app/tasks/$taskId/deliver'
    | '/app/tasks/$taskId/rate'
    | '/app/tasks/$taskId/review'
    | '/app/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/sitemap.xml'
    | '/app/alumni-pro'
    | '/app/assessments'
    | '/app/browse'
    | '/app/internships'
    | '/app/learn'
    | '/app/mentorship'
    | '/app/messages'
    | '/app/notifications'
    | '/app/partnership'
    | '/app/subscription'
    | '/app/talent'
    | '/app/wallet'
    | '/auth/login'
    | '/auth/signup'
    | '/app/'
    | '/app/learn/$courseId'
    | '/app/mentorship/$serviceId'
    | '/app/mentorship/bookings'
    | '/app/mentorship/manage'
    | '/app/messages/$conversationId'
    | '/app/payment/$taskId'
    | '/app/profile/$userId'
    | '/app/rooms/$roomId'
    | '/app/tasks/create'
    | '/api/public/webhooks/paystack'
    | '/app/tasks/$taskId/analytics'
    | '/app/tasks/$taskId/applicants'
    | '/app/tasks/$taskId/deliver'
    | '/app/tasks/$taskId/rate'
    | '/app/tasks/$taskId/review'
    | '/app/tasks/$taskId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ApiPublicWebhooksPaystackRoute: typeof ApiPublicWebhooksPaystackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/wallet': {
      id: '/app/wallet'
      path: '/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/talent': {
      id: '/app/talent'
      path: '/talent'
      fullPath: '/app/talent'
      preLoaderRoute: typeof AppTalentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subscription': {
      id: '/app/subscription'
      path: '/subscription'
      fullPath: '/app/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/partnership': {
      id: '/app/partnership'
      path: '/partnership'
      fullPath: '/app/partnership'
      preLoaderRoute: typeof AppPartnershipRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mentorship': {
      id: '/app/mentorship'
      path: '/mentorship'
      fullPath: '/app/mentorship'
      preLoaderRoute: typeof AppMentorshipRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/learn': {
      id: '/app/learn'
      path: '/learn'
      fullPath: '/app/learn'
      preLoaderRoute: typeof AppLearnRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/internships': {
      id: '/app/internships'
      path: '/internships'
      fullPath: '/app/internships'
      preLoaderRoute: typeof AppInternshipsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/browse': {
      id: '/app/browse'
      path: '/browse'
      fullPath: '/app/browse'
      preLoaderRoute: typeof AppBrowseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assessments': {
      id: '/app/assessments'
      path: '/assessments'
      fullPath: '/app/assessments'
      preLoaderRoute: typeof AppAssessmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alumni-pro': {
      id: '/app/alumni-pro'
      path: '/alumni-pro'
      fullPath: '/app/alumni-pro'
      preLoaderRoute: typeof AppAlumniProRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks/create': {
      id: '/app/tasks/create'
      path: '/tasks/create'
      fullPath: '/app/tasks/create'
      preLoaderRoute: typeof AppTasksCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rooms/$roomId': {
      id: '/app/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/app/rooms/$roomId'
      preLoaderRoute: typeof AppRoomsRoomIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile/$userId': {
      id: '/app/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/app/profile/$userId'
      preLoaderRoute: typeof AppProfileUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payment/$taskId': {
      id: '/app/payment/$taskId'
      path: '/payment/$taskId'
      fullPath: '/app/payment/$taskId'
      preLoaderRoute: typeof AppPaymentTaskIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages/$conversationId': {
      id: '/app/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/app/messages/$conversationId'
      preLoaderRoute: typeof AppMessagesConversationIdRouteImport
      parentRoute: typeof AppMessagesRoute
    }
    '/app/mentorship/manage': {
      id: '/app/mentorship/manage'
      path: '/manage'
      fullPath: '/app/mentorship/manage'
      preLoaderRoute: typeof AppMentorshipManageRouteImport
      parentRoute: typeof AppMentorshipRoute
    }
    '/app/mentorship/bookings': {
      id: '/app/mentorship/bookings'
      path: '/bookings'
      fullPath: '/app/mentorship/bookings'
      preLoaderRoute: typeof AppMentorshipBookingsRouteImport
      parentRoute: typeof AppMentorshipRoute
    }
    '/app/mentorship/$serviceId': {
      id: '/app/mentorship/$serviceId'
      path: '/$serviceId'
      fullPath: '/app/mentorship/$serviceId'
      preLoaderRoute: typeof AppMentorshipServiceIdRouteImport
      parentRoute: typeof AppMentorshipRoute
    }
    '/app/learn/$courseId': {
      id: '/app/learn/$courseId'
      path: '/$courseId'
      fullPath: '/app/learn/$courseId'
      preLoaderRoute: typeof AppLearnCourseIdRouteImport
      parentRoute: typeof AppLearnRoute
    }
    '/app/tasks/$taskId/': {
      id: '/app/tasks/$taskId/'
      path: '/tasks/$taskId'
      fullPath: '/app/tasks/$taskId/'
      preLoaderRoute: typeof AppTasksTaskIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks/$taskId/review': {
      id: '/app/tasks/$taskId/review'
      path: '/tasks/$taskId/review'
      fullPath: '/app/tasks/$taskId/review'
      preLoaderRoute: typeof AppTasksTaskIdReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks/$taskId/rate': {
      id: '/app/tasks/$taskId/rate'
      path: '/tasks/$taskId/rate'
      fullPath: '/app/tasks/$taskId/rate'
      preLoaderRoute: typeof AppTasksTaskIdRateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks/$taskId/deliver': {
      id: '/app/tasks/$taskId/deliver'
      path: '/tasks/$taskId/deliver'
      fullPath: '/app/tasks/$taskId/deliver'
      preLoaderRoute: typeof AppTasksTaskIdDeliverRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks/$taskId/applicants': {
      id: '/app/tasks/$taskId/applicants'
      path: '/tasks/$taskId/applicants'
      fullPath: '/app/tasks/$taskId/applicants'
      preLoaderRoute: typeof AppTasksTaskIdApplicantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks/$taskId/analytics': {
      id: '/app/tasks/$taskId/analytics'
      path: '/tasks/$taskId/analytics'
      fullPath: '/app/tasks/$taskId/analytics'
      preLoaderRoute: typeof AppTasksTaskIdAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/webhooks/paystack': {
      id: '/api/public/webhooks/paystack'
      path: '/api/public/webhooks/paystack'
      fullPath: '/api/public/webhooks/paystack'
      preLoaderRoute: typeof ApiPublicWebhooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppLearnRouteChildren {
  AppLearnCourseIdRoute: typeof AppLearnCourseIdRoute
}

const AppLearnRouteChildren: AppLearnRouteChildren = {
  AppLearnCourseIdRoute: AppLearnCourseIdRoute,
}

const AppLearnRouteWithChildren = AppLearnRoute._addFileChildren(
  AppLearnRouteChildren,
)

interface AppMentorshipRouteChildren {
  AppMentorshipServiceIdRoute: typeof AppMentorshipServiceIdRoute
  AppMentorshipBookingsRoute: typeof AppMentorshipBookingsRoute
  AppMentorshipManageRoute: typeof AppMentorshipManageRoute
}

const AppMentorshipRouteChildren: AppMentorshipRouteChildren = {
  AppMentorshipServiceIdRoute: AppMentorshipServiceIdRoute,
  AppMentorshipBookingsRoute: AppMentorshipBookingsRoute,
  AppMentorshipManageRoute: AppMentorshipManageRoute,
}

const AppMentorshipRouteWithChildren = AppMentorshipRoute._addFileChildren(
  AppMentorshipRouteChildren,
)

interface AppMessagesRouteChildren {
  AppMessagesConversationIdRoute: typeof AppMessagesConversationIdRoute
}

const AppMessagesRouteChildren: AppMessagesRouteChildren = {
  AppMessagesConversationIdRoute: AppMessagesConversationIdRoute,
}

const AppMessagesRouteWithChildren = AppMessagesRoute._addFileChildren(
  AppMessagesRouteChildren,
)

interface AppRouteChildren {
  AppAlumniProRoute: typeof AppAlumniProRoute
  AppAssessmentsRoute: typeof AppAssessmentsRoute
  AppBrowseRoute: typeof AppBrowseRoute
  AppInternshipsRoute: typeof AppInternshipsRoute
  AppLearnRoute: typeof AppLearnRouteWithChildren
  AppMentorshipRoute: typeof AppMentorshipRouteWithChildren
  AppMessagesRoute: typeof AppMessagesRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPartnershipRoute: typeof AppPartnershipRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
  AppTalentRoute: typeof AppTalentRoute
  AppWalletRoute: typeof AppWalletRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPaymentTaskIdRoute: typeof AppPaymentTaskIdRoute
  AppProfileUserIdRoute: typeof AppProfileUserIdRoute
  AppRoomsRoomIdRoute: typeof AppRoomsRoomIdRoute
  AppTasksCreateRoute: typeof AppTasksCreateRoute
  AppTasksTaskIdAnalyticsRoute: typeof AppTasksTaskIdAnalyticsRoute
  AppTasksTaskIdApplicantsRoute: typeof AppTasksTaskIdApplicantsRoute
  AppTasksTaskIdDeliverRoute: typeof AppTasksTaskIdDeliverRoute
  AppTasksTaskIdRateRoute: typeof AppTasksTaskIdRateRoute
  AppTasksTaskIdReviewRoute: typeof AppTasksTaskIdReviewRoute
  AppTasksTaskIdIndexRoute: typeof AppTasksTaskIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlumniProRoute: AppAlumniProRoute,
  AppAssessmentsRoute: AppAssessmentsRoute,
  AppBrowseRoute: AppBrowseRoute,
  AppInternshipsRoute: AppInternshipsRoute,
  AppLearnRoute: AppLearnRouteWithChildren,
  AppMentorshipRoute: AppMentorshipRouteWithChildren,
  AppMessagesRoute: AppMessagesRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPartnershipRoute: AppPartnershipRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
  AppTalentRoute: AppTalentRoute,
  AppWalletRoute: AppWalletRoute,
  AppIndexRoute: AppIndexRoute,
  AppPaymentTaskIdRoute: AppPaymentTaskIdRoute,
  AppProfileUserIdRoute: AppProfileUserIdRoute,
  AppRoomsRoomIdRoute: AppRoomsRoomIdRoute,
  AppTasksCreateRoute: AppTasksCreateRoute,
  AppTasksTaskIdAnalyticsRoute: AppTasksTaskIdAnalyticsRoute,
  AppTasksTaskIdApplicantsRoute: AppTasksTaskIdApplicantsRoute,
  AppTasksTaskIdDeliverRoute: AppTasksTaskIdDeliverRoute,
  AppTasksTaskIdRateRoute: AppTasksTaskIdRateRoute,
  AppTasksTaskIdReviewRoute: AppTasksTaskIdReviewRoute,
  AppTasksTaskIdIndexRoute: AppTasksTaskIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  ApiPublicWebhooksPaystackRoute: ApiPublicWebhooksPaystackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
